#!/usr/bin/env perl

use lib 'lib';
use Test::Most;
use HTML::TokeParser::Corinna;

my $test_html = <<'END_HTML';
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>
	<head>
		<!-- This is a comment -->
		<title>This is a title</title>
		<?php 
			print "<!-- this is generated by php -->";
		?>
	</head>
	<body alink="#0000ff" bgcolor="#ffffff">
		<h1>Do not edit this HTML lest the tests fail!!!</h1>
	</body>
</html>
END_HTML
ok my $parser = HTML::TokeParser::Corinna->new( html => $test_html ),
  'We should be able to create a new parser';

my $token = $parser->get_tag('body');
eq_or_diff $token->attr, { alink => "#0000ff", bgcolor => "#ffffff" },
  '... and it should be able to parse the file';

my $tokens = $parser->peek(2);
explain ref $tokens;
explain scalar @$tokens;
explain $tokens->[0]->to_string;
explain $tokens->[1]->to_string;

throws_ok { $parser->no_such_method }
'HTML::TokeParser::Corinna::Exception::MethodNotFound',
  'The parser can throw MethodNotFound exceptions';
explain $@->to_string;

done_testing;
